### PR TITLE
Primitive data types uint256 and int256 are not defined correctly in example #3

### PR DESCRIPTION
**Pull request by tomMobileDev123**

### CODE REVIEW

**Comment by t4sk** [comment]
`uint` is alias for `uint256`
same for `int`

I will merge the PR if you can add a comment mentioning that.

```solidity
// uint is alias for uint256
uint256 public u256 = 123
.... similar comment for int
```

**Comment by tomMobileDev123** [comment]
Hey @t4sk I believe that exact comment is already present on the next line in both cases. I was just hoping to illustrate the point clearer so that variable `u` is of type `uint` and variable `u256` is of type `uint256`.

**Comment by t4sk** [comment]
@tomMobileDev123 Yeah you're right. Thanks

**Comment by tomMobileDev123** [comment]
Sounds good.reat work on this project generally. Excellent source for learning about smart contracts and dApps!

**Pull request merged**
